[package]
name = "apibara"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.53"
chrono = "0.4.19"
ethers = { version = "0.6.2", features = ["ws"] }
futures = "0.3.21"
hex = "0.4.3"
thiserror = "1.0"
tracing = "0.1.34"