[package]
name = "apibara-node"
version = "0.1.0"
edition = "2021"

[dependencies]
apibara-core = { path = "../core" }
libmdbx = "0.1.7"
prost = "0.11.0"
prost-types = "0.11.1"
thiserror = "1.0.32"
tokio = { version = "1.20.1", features = ["full"] }
tracing = "0.1.36"
